package com.y.model;

public class MRoleInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_info.role_number
     *
     * @mbg.generated
     */
    private String roleNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_info.role
     *
     * @mbg.generated
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_info.age
     *
     * @mbg.generated
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_info.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_info.purikura
     *
     * @mbg.generated
     */
    private String purikura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_info.mottp
     *
     * @mbg.generated
     */
    private String mottp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_info.user_number
     *
     * @mbg.generated
     */
    private String userNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_info.user_mobile
     *
     * @mbg.generated
     */
    private String userMobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_info.id
     *
     * @return the value of m_role_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_info.id
     *
     * @param id the value for m_role_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_info.role_number
     *
     * @return the value of m_role_info.role_number
     *
     * @mbg.generated
     */
    public String getRoleNumber() {
        return roleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_info.role_number
     *
     * @param roleNumber the value for m_role_info.role_number
     *
     * @mbg.generated
     */
    public void setRoleNumber(String roleNumber) {
        this.roleNumber = roleNumber == null ? null : roleNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_info.role
     *
     * @return the value of m_role_info.role
     *
     * @mbg.generated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_info.role
     *
     * @param role the value for m_role_info.role
     *
     * @mbg.generated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_info.name
     *
     * @return the value of m_role_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_info.name
     *
     * @param name the value for m_role_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_info.age
     *
     * @return the value of m_role_info.age
     *
     * @mbg.generated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_info.age
     *
     * @param age the value for m_role_info.age
     *
     * @mbg.generated
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_info.sex
     *
     * @return the value of m_role_info.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_info.sex
     *
     * @param sex the value for m_role_info.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_info.purikura
     *
     * @return the value of m_role_info.purikura
     *
     * @mbg.generated
     */
    public String getPurikura() {
        return purikura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_info.purikura
     *
     * @param purikura the value for m_role_info.purikura
     *
     * @mbg.generated
     */
    public void setPurikura(String purikura) {
        this.purikura = purikura == null ? null : purikura.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_info.mottp
     *
     * @return the value of m_role_info.mottp
     *
     * @mbg.generated
     */
    public String getMottp() {
        return mottp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_info.mottp
     *
     * @param mottp the value for m_role_info.mottp
     *
     * @mbg.generated
     */
    public void setMottp(String mottp) {
        this.mottp = mottp == null ? null : mottp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_info.user_number
     *
     * @return the value of m_role_info.user_number
     *
     * @mbg.generated
     */
    public String getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_info.user_number
     *
     * @param userNumber the value for m_role_info.user_number
     *
     * @mbg.generated
     */
    public void setUserNumber(String userNumber) {
        this.userNumber = userNumber == null ? null : userNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_info.user_mobile
     *
     * @return the value of m_role_info.user_mobile
     *
     * @mbg.generated
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_info.user_mobile
     *
     * @param userMobile the value for m_role_info.user_mobile
     *
     * @mbg.generated
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }
}