package com.y.mapper;

import java.util.List;

import com.y.model.MRoleInfo;

public interface MRoleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_role_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_role_info
     *
     * @mbg.generated
     */
    int insert(MRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_role_info
     *
     * @mbg.generated
     */
    int insertSelective(MRoleInfo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_role_info
     *
     * @mbg.generated
     */
    MRoleInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_role_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_role_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MRoleInfo record);
}