package com.y.mapper;

import java.util.List;

import com.y.model.MUserInfo;

public interface MUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_info
     *
     * @mbg.generated
     */
    int insert(MUserInfo user)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_info
     *
     * @mbg.generated
     */
    int insertSelective(MUserInfo record)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_info
     *
     * @mbg.generated
     */
    List<MUserInfo> selectByExample() throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_info
     *
     * @mbg.generated
     */
    MUserInfo selectByPrimaryKey(Integer id)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MUserInfo record)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MUserInfo record)throws Exception;

    /**
     * @Title: selectUserByMobilephone
     * @Description:通过手机号查询用户
     * @return List<MUserInfo> 返回类型 
     * @author ysx
     */
	List<MUserInfo> selectUserByMobilephone(String mobilephone) throws Exception;
}